### PR TITLE
Feature: Adds 'Report an Issue' menu option

### LINKED ISSUE #771: Add "Report an issue" option under settings gear
Our users run into issues when experimenting with Graph Explorer but they do not know where to report this. This being the case, there is need to add a report issue option that redirects the user to our GitHub repo to file an issue. This button can be located under the settings gear for now before we figure out a more appropriate position for it. 

 
[AB#7474](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7474)

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

This PR adds a 'Report an Issue' menu option in the settings dropdown.
This option redirects a user to the new issues page on the Graph Explorer repo.

Fixes #771 

### Demo

When no user is signed in 
image

When a user is signed in:
image

## Testing Instructions

* Navigate to the 'More actions' icon
* Click to see 'Report an Issue' option.
* Select option to be redirected to Graph Explorer's new issues page.

### CODE REVIEW

**Comment by thewahome** [comment]
@ElinorW what do you think about placing the report an issue button before sign in when signed in?

**Comment by ElinorW** [comment]
@thewahome and what about the select permissions option?
We leave it where it is?

**Comment by thewahome** [comment]
> @thewahome and what about the select permissions option?
> We leave it where it is?

I see what you mean... What if we move the GE related links to the bottom, with a separator and the other ones to the top? Sign out at the last position is more intuitive as it is mostly expected somewhere there

**Comment by ElinorW** [comment]
> > @thewahome and what about the select permissions option?
> > We leave it where it is?
> 
> I see what you mean... What if we move the GE related links to the bottom, with a separator and the other ones to the top? Sign out at the last position is more intuitive as it is mostly expected somewhere there

Updated change: 
_When a user isn't signed in_
image

_When a user is signed in_
image

**Review by thewahome — APPROVED** [review]

**Pull request merged**
