### PR TITLE
Task: Add Manifest Generator task for EO compliance

### PR DESCRIPTION
**Pull request by MIchaelMainer**
This Manifest Generator task is successfully running and we are capturing manifest files as pipeline artifacts.

image

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
@adhiambovivian and @ElinorW, can I get a review on this? See the results of [microsoftgraph.microsoft-graph-explorer-v4 ](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1439/checks?check_run_id=5117510674) as part of the review.

**Review by ElinorW — APPROVED** [review]

**Comment by ElinorW** [comment]
Hey @MIchaelMainer this looks good. 
Could you however hold off on merging it just yet.. 
I need to merge the latest release onto the dev branch first and I wouldn't want this to not be captured in the next release

**Comment by MIchaelMainer** [comment]
@ElinorW Which PR does this PR depend on?

**Comment by ElinorW** [comment]
> @ElinorW Which PR does this PR depend on?

this one: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1447

**Review by millicentachieng — APPROVED** [review]

**Pull request merged**
