### PR TITLE
fix: remove the replacement of escape characters in json response formatting

### LINKED ISSUE #3158: Graph Explorer does not return Json formatted output
**Describe the bug**

Graph Explorer is not returning Json formatted output. 
Endpoints being tested so far:
https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=* 
https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=appDefinitions
The same API works as expected if I pull Teams Apps information from other tenants.
My assumption is that this could be because the amount of information returned may varies. But I’m not sure.

**To Reproduce**
1. Go to (https://developer.microsoft.com/en-us/graph/graph-explorer)
GET 

https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=* 
https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=appDefinitions

4. I get a 200 OK response.
5. The output is not easy to read because it is not Json formated.

**Expected behavior**
The output being returned in Json format.

### PR DESCRIPTION
**Pull request by musale**
## Overview

Removes replacement of escaped characters in the stringified json.
closes #3158

## Testing Instructions

* run the query `https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=*`
* Check the response preview tab to have well formatted json

### CODE REVIEW

**Comment by SilasKenneth** [comment]
Tested in Safari on iOS 17.5.1
IMG_0444

**Comment by musale** [comment]
Thank you @SilasKenneth! Also tested the paths in the #895 and they work as expected.

**Review by thewahome — APPROVED** [review]

**Comment by thewahome** [comment]
@musale since the test works, the stringify -> parse is an unnecessary set of legacy steps. Is this something that we can confidently remove?

**Comment by musale** [comment]
> @musale since the test works, the stringify -> parse is an unnecessary set of legacy steps. Is this something that we can confidently remove?

Sure! Unless that telemetry is important, I don't see the need for that function too.

**Pull request merged**
