### PR TITLE
fix unformatted response preview safari

### LINKED ISSUE #620: Response preview appears unformatted in Safari
**Describe the bug**
The response preview JSON appears unformatted in Safari (no line breaks or indenting).
Choosing "Format Document" from the context menu also does not work.

**To Reproduce**
1. Go to the Graph Explorer
2. Click on "GET: my mail"
3. See unreadable blob of unformatted JSON in the response preview.
**Expected behavior**
I expect to see formatted JSON like what appears in Chrome and Edge
**Desktop:**
 - OS: macOS 10.15.5
 - Browser: Safari 13.1.1
 
[AB#6257](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6257)

### PR DESCRIPTION
**Pull request by ezkemboi**
## Overview

Fix formatting issue of JSON when using Safari Browsers
- fixes #620

### Demo

Screenshot 2020-11-17 at 23 27 04

Screenshot 2020-11-17 at 23 27 28

### Notes

Here is a function I did not use and commented it in editorDidMount prop in MonacoEditor `Have not removed yet`
```javascript
function editorDidMount(editor: any) {
  const editorHasText = !!editor.getModel().getValue();

  if (editorHasText) {
    formatDocument(editor);
  }

  editor.onDidChangeModelContent(() => {
    formatDocument(editor);
  });
}

function formatDocument(editor: any) {
  editor.getAction('editor.action.formatDocument').run();
}
```
Here is the replacement that seemed to work for all browsers
```javascript
 body = JSON.stringify(body).replace(/(?:\\[rnt]|[\r\n\t]+)+/g, '');
 // remove whitespace, tabs or raw string (Safari related issue)
 body = JSON.parse(body); // convert back to javascript object
 body = JSON.stringify(body, null, 4); // format the string (works for all browsers)
```

We can discuss more on the above code under reviews and way forward to allow all browsers to format JSON effectively. 

## Testing Instructions

* Need to be tested using Safari, Chrome, Edge, and/or another browser
* Check on the formatting of response preview [Need to be JSON format]

### CODE REVIEW

**Comment by ezkemboi** [comment]
@thewahome and @ElinorW I have a PR that can offer a room for discussion.

**Review by jobala — APPROVED** [review]
LGTM 👍

**Comment by jobala** [comment]
@ezkemboi clean up the PR and this should be good to go.

**Comment by ezkemboi** [comment]
I will be working on cleaning this one.

**Comment by ezkemboi** [comment]
Ping @jobala

**Comment by jobala** [comment]
Thanks @ezkemboi. @thewahome this fails with `azure_static_web_apps_api_token was not provided.` how can I fix this?

**Pull request merged**
