### PR TITLE
adds go to the snippet tabs

### PR DESCRIPTION
**Pull request by baywet**
## Overview

Adds Go as a snippet tab

### Demo

image

### Notes

Related https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/749

I put go last as it's in preview, but if you prefer an alphabetical order, we can move it before objective-C

## Testing Instructions

- Run devx API locally (or wait for the other PR to be merged and released)
- Update `DEVX_API_URL` to your local url. (optional, only if running devx API locally)
- `npm run start`
- open the brower to the server url
- click on `Code snippets`
- click on `Go`

### CODE REVIEW

**Comment by thewahome** [comment]
@baywet Good work on the tab. 
The code snippets seem not to be supported. The calls fail with this message.
`Message: "Specified argument was out of the range of valid values. (Parameter 'Language 'go' is not supported')"
StatusCode: 404`

**Comment by baywet** [comment]
@thewahome that's because as indicated by my initial comment it depends on https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/749

Were you running that branch of the devx Api locally when you tested it?

**Comment by thewahome** [comment]
> @thewahome that's because as indicated by my initial comment it depends on [microsoftgraph/microsoft-graph-devx-api#749](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/749)
> 
> Were you running that branch of the devx Api locally when you tested it?

No @baywet . Doing this soon.

@adhiambovivian @kristen-msft How do we get word out that there will be 'Go' support? This work should not go in without hullabaloo :-)

**Comment by baywet** [comment]
FYI now that the devx PR made it to production I did another round of validation thanks to the help of @ElinorW 
this is what it looks like, without having to change the API URL anymore.

image

**Review by thewahome — APPROVED** [review]

**Review by ElinorW — APPROVED** [review]

**Comment by baywet** [comment]
thanks for merging team! please let me know when it's deployed :)

**Pull request merged**
