### PR TITLE
Enhancement/hint when unauthenticated

### LINKED ISSUE #974: Hint users to login when they are not getting results
**Is your feature request related to a problem? Please describe.**
Sometimes users will try APIs immediately and get no results.  It's not always clear that they can/need to login on the left-hand side to get "real" data.  Even though it says so on the sample account, there might be some UX optimizations that can be made to make this more intuitive.

**Describe the solution you'd like**
Maybe a hint when no results are received, or when requests are made to APIs outside of the sample's well-known set of responses.  "Hey you can login for real results."  
[AB#9661](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9661)

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Fixes #974 

After running more than 8 queries when unauthenticated, the coachmark below appears
image
Hovering over the coachmark displays this bubble content:
image

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions
Sign out of GE.
Run 9 sample queries
A coachmark appears which prompts the user to sign in to see real data

### CODE REVIEW

**Comment by ElinorW** [comment]
Hey , could you update the testing instructions...
I was confused at the "Click on any sample queries other than GET" step...
Then I realised you meant that we should click on the GET request more than 5 times

**Comment by Onokaev** [comment]
Sure,
I’ve made the update

**Review by jobala — CHANGES_REQUESTED** [review]
@Onokaev  from the issue description the problem is that user tries to run samples **immeadiately** without knowing that they are getting sample data, showing this to the user eight requests later doesn't solve this problem. Also this issue is the reason we had the **sign in to access your own data** label on top of the login button and should be considered solved,  why are we doing this work again?

**Comment by jobala** [comment]
@Onokaev also note that this issue was resolved by [this change](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/28a58fba5109b505e73ffcd2a9264a39bb3d3d18/src/app/views/authentication/Authentication.tsx#L83) but maybe we forgot to close it then. This change was added around two days after the issue was created.

**Comment by jobala** [comment]
@Onokaev @adhiambovivian  It is possible that this issue was solved by [this change](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/28a58fba5109b505e73ffcd2a9264a39bb3d3d18/src/app/views/authentication/Authentication.tsx#L83) because it made it clear that a users need to sign in to access their data.

Before the change
image

After the change
image

**Comment by Onokaev** [comment]
> @Onokaev @adhiambovivian It is possible that this issue was solved by [this change](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/28a58fba5109b505e73ffcd2a9264a39bb3d3d18/src/app/views/authentication/Authentication.tsx#L83) because it made it clear that users need to sign in to access their data.
> 
> Before the change image
> 
> After the change image

Hi @jobala. Thanks for pointing this out. Yes, this change you've highlighted does address the issue. I am closing this PR

**Pull request closed without merging**
