### PR TITLE
Show Resource Explorer HTTP methods next to resource

### LINKED ISSUE #1322: [Resource Explorer] Display HTTP methods in Resource explorer like they are shown in Samples Queries.
image

This will allow "selecting" a resource by just clicking on the method.  No need to use context menu.
Also the context menu should allow "add to collection" for specific HTTP methods.

### PR DESCRIPTION
**Pull request by millicentachieng**
## Overview

Closes #1322

### Demo
Resource Explorer new look
image

 
Postman collection preview
image

### CODE REVIEW

**Review by ElinorW — COMMENTED** [review]
Wow, I really like the added changes! 👍🏾👏🏾

A question though, why do we use the plug disconnected icon? 
image

**Comment by ElinorW** [comment]
Also, previously on selecting 'Set Query' the query would autofill...
I'm not experiencing the same behaviour here...

image
_Image show's when a user selects GET, the Method, Version and Query are auto-filled at the top _

**Comment by millicentachieng** [comment]
> Wow, I really like the added changes! 👍🏾👏🏾
> 
> A question though, why do we use the plug disconnected icon?
 It's to indicate that a node has no children.

**Comment by millicentachieng** [comment]
> Also, previously on selecting 'Set Query' the query would autofill... I'm not experiencing the same behaviour here...
> 
> _Image show's when a user selects GET from the resource..., the Method, Version and Query are auto-filled at the top_

Clicking on the HTTP method sets the query on the run query box. I agree that it may not be that intuitive to a user and we should instead look into setting the query when the list item is clicked.

**Comment by Onokaev** [comment]
> > Also, previously on selecting 'Set Query' the query would autofill... I'm not experiencing the same behaviour here...
> > _Image show's when a user selects GET from the resource..., the Method, Version and Query are auto-filled at the top_
> 
> Clicking on the HTTP method sets the query on the run query box. I agree that it may not be that intuitive to a user and we should instead look into setting the query when the list item is clicked.

Nice work @millicentachieng! 
Good idea! We can maintain the methods and allow for setting query when a list item is clicked

**Comment by millicentachieng** [comment]
> Also, there is a small issue with the localization:
> 
> In PathsReview.tsx file line 84, the id passed to FormatMessage has been truncated (It's in 2 lines). Having it on one line will solve the localization error.

Good catch, @Onokaev!

**Comment by ElinorW** [comment]
> > Wow, I really like the added changes! 👍🏾👏🏾
> > A question though, why do we use the plug disconnected icon?
> 
> It's to indicate that a node has no children.

Oh I see... I'm not sure it's very intuitive.. for instance I didn't get that. Can't it just stay without the icon?

**Comment by millicentachieng** [comment]
> > > Wow, I really like the added changes! 👍🏾👏🏾
> > > A question though, why do we use the plug disconnected icon?
> > 
> > 
> > It's to indicate that a node has no children.
> 
> Oh I see... I'm not sure it's very intuitive.. for instance I didn't get that. Can't it just stay without the icon?

That's a good point. It might cause more confusion to our users than being informative. @thewahome can give us his reasons but I'll remove the icons for now.

**Comment by ElinorW** [comment]
Also some suggestions, 
1) could there be a confirmation that an item has been added to the collection. I believe it would help users who navigate with a screen reader for example. 
2) When a user presses enter on the resource e.g. GET admin, could it also set the query the same way it does when you click on it? This would make it easier for user's who use keyboard for navigation.

**Comment by millicentachieng** [comment]
> Also some suggestions,
> 
> 1. could there be a confirmation that an item has been added to the collection. I believe it would help users who navigate with a screen reader for example.
> 2. When a user presses enter on the resource e.g. GET admin, could it also set the query the same way it does when you click on it? This would make it easier for users who use a keyboard for navigation.

Good insights, @ElinorW. I have created a [new issue](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1394) to track the first item. The second item's done.

**Review by ElinorW — APPROVED** [review]

**Pull request merged**
