### PR TITLE
Fix: Update a Code snippet when request body is updated

### LINKED ISSUE #1935: Code Snippets are not showing the construction of request bodies
e.g. 
image

I'm pretty sure we used to construct an object for request bodies.  Can someone investigate why we are not creating an example object based on the request body schema?  

@andrueastman Can you confirm my recollection that we used to do this?

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

Fixes #1935 
Update snippet when request body is updated

## Testing Instructions

* Navigate to **Applications**
* Select 'POST create a new application
* Observe Code snippets tab ( e.g. C#)
* Update request body
* Click on a different Code snippet (e.g. JavaScript) 
* Observe updated request body object.

### CODE REVIEW

**Comment by ElinorW** [comment]
> Good stuff! There's a small regression on the request method. It does not change when you click on the samples.

Yikes, I'll have a look at this

**Comment by ElinorW** [comment]
> > Good stuff! There's a small regression on the request method. It does not change when you click on the samples.
> 
> Yikes, I'll have a look at this

Hey @Onokaev , I'm unable to reproduce this. Can you confirm if it's still the case?

**Comment by Onokaev** [comment]
> > > Good stuff! There's a small regression on the request method. It does not change when you click on the samples.
> > 
> > 
> > Yikes, I'll have a look at this
> 
> Hey @Onokaev , I'm unable to reproduce this. Can you confirm if it's still the case?

Yes. Try clicking POST or PATCH samples under Applications. The request method does not change

**Comment by ElinorW** [comment]
Upon further research, I noticed the code snippet will update when a user run's the query.

**Pull request closed without merging**
